create database sue;
use sue;
CREATE TABLE NEWS(
COMPANY VARCHAR(100) NOT NULL,
IMAGE LONGTEXT NOT NULL,
TITLE VARCHAR(200) NOT NULL,
LINK LONGTEXT NOT NULL,
POST DATETIME NOT NULL,
FIELD VARCHAR(100) NULL,
REPORTER VARCHAR(100) NULL,
SUMMARY_Short LONGTEXT NOT NULL,
SUMMARY_Middle LONGTEXT NOT NULL,
SUMMARY_Long LONGTEXT NOT NULL);

use sue;

select * from news;

#DROP TABLE news;